messages:

  # 접두사
  prefix: "&a[공지]&r "

  auto_notice:

    # 도움말
    help:
      - "/자동공지 생성 <공지 이름>" # starly.notice.create
      - "/자동공지 제거 <공지 이름>" # starly.notice.remove
      - "/자동공지 활성여부 <공지 이름>" # starly.notice.toggle
      - "/자동공지 내용수정 <공지 이름> <내용>" # starly.notice.edit.contents
      - "/자동공지 시간설정 <공지 이름> <시간>" # starly.notice.edit.time

    # 생성
    create: "공지 {name} 을/를 생성했습니다."

    # 제거
    remove: "공지 {name} 을/를 제거했습니다."

    # 활성 여부
    toggle_on: "공지 {name}을/를 활성화했습니다."
    toggle_off: "공지 {name}을/를 비활성화했습니다."

    # 내용수정
    editContents: "{name} 의 공지 내용을 '{contents}' (으)로 수정했습니다."

    # 시간설정
    editTime: "{name} 의 공지 시간을 {time} (으)로 설정했습니다."


errorMessages:

  # 권한이 없을 때 출력 되는 메세지
  noPermission: "&c명령어를 사용할 수 있는 권한이 없습니다."

  # 잘못 된 커맨드 사용 시 출력 되는 메세지
  wrongCommand: "&c잘못 된 사용법입니다."

  # 공지 이름이 없을 경우 출력 되는 메세지
  noName: "&c이름을 입력하세요."

  # 특수문자가 포함되는 경우 출력 되는 메세지
  invalidName: "&c이름에는 특수문자를 사용할 수 없습니다!"

  # 공지가 존재할 경우 출력 되는 메세지
  existNotice: "&c이미 존재하는 공지입니다."

  # 공지가 존재하지 않는 경우 출력 되는 메세지
  notExistNotice: "&c존재하지 않는 공지입니다."

  # 공지 내용을 입려하기 않았을 때 출력 되는 메세지
  noContents: "&c공지 내용을 입력해주세요."

  # 시간을 입력하지 않을 경우 출력 되는 메세지
  noTime: "&c시간을 입력해주세요."

others:

  # 공지가 보내질 때 재생되는 사운드
  sound:
    # 사운드
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    # 볼륨
    volume: 1
    # 피치
    pitch: 1
