name: ST-AutoNotice
main: net.starly.autonotice.AutoNoticeMain
author: Starly Team
website: http://starly.kr/discord

description: AutoNotice Plugin.

softdepend:
  - ST-Core

version: 1.0.0_Alpha
api-version: 1.13

commands:
  notice:
    aliases: ["공지"]
  autonotice:
    aliases: ["자동공지"]